---
<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/pandas_logo.png" alt="Drawing" style="width:900px;">

# PANDAS COMPLEMENTS

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()
pd.__version__

'1.1.4'

## <span style="color:green"> If you are in colaboratoy </span>:

In [2]:
#@title 1. MONTAR EL DRIVE { display-mode: "form" }
import os
from google.colab import drive
drive.mount('/content/drive')
os.chdir('/content/drive/My Drive/course-IA1/ai-uis-student')
print(os.getcwd())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/course-IA1/ai-uis-student

Load dataset

In [3]:
d = pd.read_csv("data/california_housing_train.csv")
type(d)

pandas.core.frame.DataFrame

# <span style="color:red"> 1. Pivot tables </span>

Pivot tables help to group and summarize dataFrame information, showing information in comapact way. 

For instance, to group and summarize the avergage of houses regarding to the number of ages, we follow next instructions:

In [4]:
table = pd.pivot_table(d,index=["housing_median_age"],values=["median_house_value"])
table.head(5)

                    median_house_value
housing_median_age
1.0                      190250.000000
2.0                      229438.836735
3.0                      239450.043478
4.0                      230054.105590
5.0                      211035.708543

We can also use other mathematical functions, by using  the parameter `aggfunc`. For example, in addition to the average value, we want to know the number of houses and the sum of all the values of the houses by age number. Also, the `margins` parameter calculates total numbers at the end of the table.

In [5]:
table = pd.pivot_table(d,index=["housing_median_age"],values=["median_house_value"],
               aggfunc=[np.mean, np.sum, len], margins=True)
table.head(10)

                                 mean                sum                len
                   median_house_value median_house_value median_house_value
housing_median_age
1.0                     190250.000000           380500.0                2.0
2.0                     229438.836735         11242503.0               49.0
3.0                     239450.043478         11014702.0               46.0
4.0                     230054.105590         37038711.0              161.0
5.0                     211035.708543         41996106.0              199.0
6.0                     206768.240310         26673103.0              129.0
7.0                     188445.059603         28455204.0              151.0
8.0                     190805.073034         33963303.0              178.0
9.0                     190306.994186         32732803.0              172.0
10.0                    178416.393805         40322105.0              226.0

# <span style="color:red"> 2. Pandas profiler </span>

`Pandas_profiling` is a tool that provides a more detailed analysis of the dataset in a fast and easy way.
In its reports it provides missing values, histograms, correlations, descriptive statistics and generates alerts when it finds high correlations and variables with many missing values.

In [10]:
import pandas_profiling
import pandas.testing as tm

A report (like `describe()`) is generated as follows:

In [ ]:
#@title sometimes neccesary to use last version of pandas
!pip install -U pandas-profiling

In [6]:
# Utility function that come in handy when working with Jupyter notebooks
#d.profile_report(style={'full_width':True})
from pandas_profiling import ProfileReport

report = ProfileReport(d, title='Pandas Profiling Report', html={'style':{'full_width':True}})

# Report
#report = pandas_profiling.ProfileReport()

In [7]:
report

Output hidden; open in https://colab.research.google.com to view.

---
<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/bannerThanks.jpg" alt="Drawing" style="width:700px;">