<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/banner_IA.png"  width="1000px" height="200px">


# **Taller:** Métodos *no* supervisados

## <span style="color:red"> Outline </span>

1. [Ejercicio 1.](#eje1)
2. [Ejercicio 2.](#eje2)
3. [Ejercicio 3.](#eje3)

In [ ]:
#@title **Cargando las librerías**
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## **Ejercicio 1:** Utilizando PCA 📊👩‍🏫 <a name="eje1"></a>


El análisis de componentes principales **(PCA)** permite reducir la dimensionalidad de datos preservando la mayor cantidad de varianza posible.
<img src="https://media.licdn.com/dms/image/v2/D5612AQGOtNZfBPC-5A/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1665494667582?e=2147483647&v=beta&t=hGQ8lu-v0oX2nStNd-FDh0lyl4ix8U9uPIpEr3TT_WE">

1. Carga un dataset proveído por sklearn basado en dígitos (``sklearn.datasets.load_digits``).
2. Aplica PCA conservando el **90%, el 95% y el 99% de la varianza.** (📌 **Recuerda:** es necesario cambiar los parámetros del método...)
  - Calcula la varianza para cada componente (📌**Recuerda:** para ello puedes guiarte del parámetro `explained_variance_ratio_ndarray`)
  - Realiza el **scree plot** en donde muestre el porcentaje de importancia para cada componente
  - Plotea el resultado con las dos componentes más influyentes
3. **Reconstruye** las imágenes originales desde la proyección PCA. (📌 **Recuerda:** para ello puedes guiarte de `inverse_transform`)
4. **Muestra** las imágenes originales y reconstruidas lado a lado (al menos 10 ejemplos).
5. **Calcula** el **error cuadrático medio** de reconstrucción para todos los ejemplos.

🤔Pregunta adicional: ¿Qué representa cada componente principal en el contexto de estas imágenes y qué tipo de información se pierde tras la reducción?

In [ ]:
#@title **CODE:** student time 🤓👆

from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import numpy as np

## **Ejercicio 2:** Utilizando K-means 📊👩‍🏫 <a name="eje2"></a>

Estás trabajando con un conjunto de datos multidimensionales y deseas aplicar un modelo no supervisado para tratar con ellos. Tu objetivo es encontrar el número óptimo de clusters usando K-means y el método del codo (elbow method).

<img src="https://datarundown.com/wp-content/uploads/2023/09/k-means-clustering-algorithm-in-machine-learning.png">

1. Utiliza el dataset de dígitos de ``sklearn.datasets.load_digits``.
2. Calcula la **inercia** de K-means para valores de 𝑘 entre `2` y `20`.
3. Grafica la curva de **inercia** y determina visualmente el "codo".
4. Calcula el **Silhouette Score** para los mismos valores de 𝑘 y grafícalo.

¿Coincide el codo de la curva de inercia con el valor máximo del Silhouette Score?
¿Qué diferencias observas entre los valores de inercia y los Silhouette Scores?
¿Cuál métrica te parece más confiable para este conjunto?
¿Qué harías si los dos métodos no coinciden?

In [ ]:
#@title **CODE:** student time 🤓👆

from sklearn.datasets import load_digits
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
import numpy as np

# **Dataset aves**
Para poder identificar el tipo de ave, es necesario poder ver su morfología, por lo cual, el siguiente dataset, presenta las siguientes características:

- `id`:	Identificador único del espécimen
- `huml`:	Longitud del húmero
- `humw`:	Ancho del húmero
- `ulnal`:	Longitud del cúbito
- `ulnaw`:	Ancho del cúbito
- `feml`:	Longitud del fémur
- `femw`:	Ancho del fémur
- `tibl`:	Longitud de la tibia
- `tibw`:	Ancho de la tibia
- `tarl`:	Longitud del tarso (parte del pie)
- `tarw`:	Ancho del tarso
- `type`:	**Categoría** del ave (por ejemplo, especie, subespecie, o zona geográfica: SW, SO, etc.)

<img src="https://www.eurokidsindia.com/blog/wp-content/uploads/2024/08/different-types-of-birds.jpg">

In [ ]:
bird_df = pd.read_csv("https://drive.google.com/uc?id=1_hUnXksDf2GoPYDoJcwU989L6ZV4oyB3")
bird_df

,id,huml,humw,ulnal,ulnaw,feml,femw,tibl,tibw,tarl,tarw,type
0,0,80.78,6.68,72.01,4.88,41.81,3.70,5.50,4.03,38.70,3.84,SW
1,1,88.91,6.63,80.53,5.59,47.04,4.30,80.22,4.51,41.50,4.01,SW
2,2,79.97,6.37,69.26,5.28,43.07,3.90,75.35,4.04,38.31,3.34,SW
3,3,77.65,5.70,65.76,4.77,40.04,3.52,69.17,3.40,35.78,3.41,SW
4,4,62.80,4.84,52.09,3.73,33.95,2.72,56.27,2.96,31.88,3.13,SW
...,...,...,...,...,...,...,...,...,...,...,...,...
415,415,17.96,1.63,19.25,1.33,18.36,1.54,31.25,1.33,21.99,1.15,SO
416,416,19.21,1.64,20.76,1.49,19.24,1.45,33.21,1.28,23.60,1.15,SO
417,417,18.79,1.63,19.83,1.53,20.96,1.43,34.45,1.41,22.86,1.21,SO
418,418,20.38,1.78,22.53,1.50,21.35,1.48,36.09,1.53,25.98,1.24,SO
419,419,17.89,1.44,19.26,1.10,17.62,1.34,29.81,1.24,21.69,1.05,SO

In [ ]:
bird_df.groupby('type').count()['id']

type
P      38
R      50
SO    128
SW    116
T      23
W      65
Name: id, dtype: int64

## **Ejercicio 3:** Extracción del embebido <a name="eje3"></a> 📊👩‍🏫
Entrenar una red neuronal para clasificar el **tipo de ave** y extraer el embedding latente aprendido antes de la capa de salida

1. **Preprocesamiento**:
  - Cargar los datos.
  - **Elimina** la columna `id` y los valores `NaN`
  - **Separar** variables numéricas (X) y la etiqueta (type).
  - **Codificar** la clase (type) como entero.
  - **Escalar** los datos numéricos con StandardScaler.

2. **Construcción** del modelo DNN pero con [API funcional](https://keras.io/guides/functional_api/)
  - **Capa de entrada → Capa oculta** (realiza tu red a tu gustoxd) **→ Capa embebida (bottleneck) → Capa de salida.**
  - Usar **activaciones** relu y softmax (o sigmoid si es binaria).

  ```
  # 2. Construir el modelo con API Funcional
  inputs = layers.Input(shape=(X.shape[1],))
  x = layers.Dense(64, activation='relu')(inputs)
  x = layers.Dense(16, activation='relu', name='embedding')(x)  # capa embebida
  outputs = layers.Dense(6, activation='softmax')(x)  # 6 clases
  model = models.Model(inputs=inputs, outputs=outputs)

  optimizer = Adam(learning_rate=0.0005)  # o incluso 0.0005
  model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
  model.summary()
  ```

3. **Entrenamiento**:
  - Entrenar el modelo por pocas épocas.
  - Evaluar exactitud en los datos.

  ```
  # 3. Entrenar
  model.fit(X_scaled, y_encoded, epochs=10, batch_size=16, verbose=1)
  ```

4. **Extracción del embedding**:
  - Usar Model de Keras para definir una red truncada hasta la capa embebida.
  - Extraer las representaciones intermedias y visualizalas

  ```
  # 4. Extraer embebido
  embedding_model = models.Model(inputs=model.input, outputs=model.get_layer('embedding').output)
  X_embedded = embedding_model.predict(X_scaled)
  ```


5. **Visualizar** el embebido por medio de t-SNE y PCA.

In [1]:
#@title **CODE:** student time 🤓👆
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers, models, optimizers
from sklearn.preprocessing import LabelEncoder, StandardScaler

bird_df = pd.read_csv("https://drive.google.com/uc?id=1_hUnXksDf2GoPYDoJcwU989L6ZV4oyB3")

---
<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/bannerThanks.jpg" alt="Drawing" style="width:700px;"/>